### ISSUE TITLE
Ready to use?

### ISSUE THREAD

**Issue by ursbraem** [superextinct/hfg-newsletter2go#1]
Hallo Niklas

Ich möchte nl2go in eine Craft-Site einbinden und lieber nicht ihr "All-Inclusive"-JS Snippet nutzen. Da habe ich dies gefunden.

Würdest du den Produktiv-Einsatz deines Plugins empfehlen? Ist es schon so weit, und wirst du es auch in Zukunft maintainen?

Schöne Ostern
Urs

**Comment by superextinct** [comment]
Hallo Urs,

das Plugin war ursprünglich dafür gedacht, mit dem API-Endpunkt `Submit Form / Subscribe Contact` zu kommunzieren. Der ist allerdings in der jetzigen Version nicht fünktionstüchtig, da keine Form ID übergeben wird, daher hab ich die Entwicklung nicht weiter verfolgt. Der ursprüngliche Use Case lässt sich viel unkomplizierter umsetzen, ganz ohne API-Authentifzierung:

```js
const data = new FormData(this.form);
const formID = "…"; 

Axios.post("https://api.newsletter2go.com/forms/submit/"+ formID.toLowerCase() +"?type=subscribe", {
    recipient: {
        email: data.get("recipientEmail"),
        first_name: data.get("recipientName"),
        // …
    }
})
.then( function(response) {
    if (response.status == 201 || response.status == 200) {
        // Success
    } else {
        // Error
        console.error(response);
    }
});
```

Niklas

**Comment by ursbraem** [comment]
Oh, danke! Hast du vielleicht ohne Aufwand deinerseits auch noch das form markup dazu? Vielleicht auf einer Prod. Site?

**Comment by superextinct** [comment]
Ja, schau hier mal im Footer: [https://www.hfg-gmuend.de/](https://www.hfg-gmuend.de/)

**Comment by ursbraem** [comment]
Danke vielstmals!!!
